// <auto-generated />
using System;
using FluxoCaixa.Consolidado.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FluxoCaixa.Consolidado.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ConsolidadoWriteDbContext))]
    [Migration("20260912233553_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FluxoCaixa.Consolidado.Domain.Entities.SaldoDiario", b =>
                {
                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<decimal>("TotalCreditos")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_creditos");

                    b.Property<decimal>("TotalDebitos")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_debitos");

                    b.HasKey("Data")
                        .HasName("pk_saldo_diario");

                    b.ToTable("saldo_diario", (string)null);
                });

            modelBuilder.Entity("FluxoCaixa.Consolidado.Infrastructure.Persistence.ProcessedEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("ProcessadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processado_em");

                    b.HasKey("EventId")
                        .HasName("pk_processed_events");

                    b.ToTable("processed_events", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
